name: "Perform Initial Repository Setup"

on:
  push:
    branches: [main]

jobs:
  pre:
    name: "Setup Repository"
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.pre.outputs.skip }}
    steps:
    - name: "Checkout"
      uses: actions/checkout@v4

    - name: "Precondition Check"
      id: pre
      run: |
        export RFC_NAME=$(make RFC_NAME)
        if ! ls mydraft* 2>/dev/null | grep -qv mydraft.org; then
          {
            echo "------------------------------------------------------------"
            echo "Skipping setup for the first commit."
            echo
            echo "Rename mydraft.org to start using this repository:"
            echo
            echo "> https://github.com/${{github.repository}}/edit/main/mydraft.org"
            echo
            echo "Change the name of the file and its title."
            echo "Commit the changes to the 'main' branch."
            echo
            echo "------------------------------------------------------------"
          } >>"$GITHUB_STEP_SUMMARY"
          echo "skip=true" >>"$GITHUB_OUTPUT"
        elif [ ! "$RFC_NAME" = "draft-myname-wg-org-template" ]; then
          {
            echo "------------------------------------------------------------"
            echo "Skipping setup for an already-configured repository."
            echo
            echo "Delete .github/workflows/setup.yml to avoid running this action:"
            echo
            echo "> https://github.com/${{github.repository}}/delete/main/.github/workflows/setup.yml"
            echo
            echo "------------------------------------------------------------"
          } >>"$GITHUB_STEP_SUMMARY"
          echo "skip=true" >>"$GITHUB_OUTPUT"
        else
          echo "skip=false" >>"$GITHUB_OUTPUT"
        fi

  setup:
    name: "Initialize Repository"
    runs-on: ubuntu-latest
    needs: pre
    if: ${{ needs.pre.outputs.skip != 'true' }}
    permissions:
      contents: write
    steps:
    - name: "Checkout"
      uses: actions/checkout@v4

    - name: "Git Config"
      run: |
        git config user.email "idbot@example.com"
        git config user.name "I-D Bot"

    - name: "Cleanup"
      run: |
        git rm -rf .github/workflows/setup.yml
        git commit -m "Remove setup files"

    - name: Prepare Deployment Directory
      run: |
        mkdir -p deploy
        run: pandoc README.org -o deploy/index.html

    - name: "Update GitHub Pages"
      uses: martinthomson/i-d-template@v1
      with:
        make: gh-pages

    - name: "Push Changes"
      run: |
        git push
